version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - idpass-net

  redis:
    image: redis:latest
    container_name: idpass-redis
    networks:
      - idpass-net

  back:
    build: ./idpass-java
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - C:/Users:/app/local_users
      - C:/Users/SSAFY/Desktop/IDPass:/app/output
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NAVER_OCR_SECRET_KEY=${NAVER_OCR_SECRET_KEY}
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - idpass-net

  front:
    build:
      context: ./idpass-front
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:80"
    container_name: frontend
    networks:
      - idpass-net

  nginx:
    build: ./nginx
    container_name: idpass-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=${SERVER_NAME} # nginx.conf에서 쓸 도메인 변수 [cite: 2026-02-02]
    depends_on:
      - back
      - front
    networks:
      - idpass-net

networks:
  idpass-net:
    driver: bridge