events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # HTTP (80) -> HTTPS (443) 리다이렉트
    server {
        listen 80;
        server_name localhost; 

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # HTTPS (443) 실제 운영
    server {
        listen 443 ssl;
        server_name localhost;

        # SSL 인증서 (Certbot 경로)
        ssl_certificate /etc/letsencrypt/live/localhost/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/localhost/privkey.pem;

        # 프론트엔드 연결 (React)
        location / {
            proxy_pass http://front:5173; 
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # 백엔드 연결 (Spring Boot API)
        location /api/ {
            proxy_pass http://back:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}