spring.application.name=idpass-java

# Naver CLOVA OCR ?? ??
# APIGW Invoke URL
naver.ocr.invoke-url=https://ir06s7tvz8.apigw.ntruss.com/custom/v1/50438/257a04d0d44ad8a1650fe050ae9f86f85c9fe4d704fc826d58edb207dad8d468/general
# Secret Key
naver.ocr.secret-key=RFVhUU9VdFBFbnRrS1VzQ2p3ZGlXeHVST0FuQ1FvbXM=

# ?? ??? ?? (??? ??? ??)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB